import { useState, useCallback, useEffect, useMemo, useRef } from 'react'
import BottomNav from './components/BottomNav'
import Toast from './components/Toast'
import Dashboard from './pages/Dashboard'
import Transactions from './pages/Transactions'
import Settings from './pages/Settings'
import Checklist from './pages/Checklist'
import Onboarding from './pages/Onboarding'
import { maybeNotifyDueBills } from './utils/notify'
import {
  getAccessToken, getAccessTokenSilent, syncTransactionsToSheet, syncBillingCyclesToSheet, syncMonthlyPlanToSheet,
} from './utils/googleSheetSync'
import { fetchImportRows, toISODate as toImportISODate } from './utils/importSheetSync'
import { nextOccurrence, daysUntil, formatMD, statusForDaysLeft, dayFromMD } from './utils/recurrence'
import { applyCycleUpdate, ensureBillingCycles, unpaidCycles, totalUnpaid, daysUntilDue } from './utils/billingCycles'
import {
  daysUntilDue as daysUntilPlanDue,
  duePlanOccurrences,
  installmentPaidCount,
  materializeDuePlanTransactions,
  nextDueOccurrence,
  upcomingUnmaterializedInWindow,
  IMPORT_MATCH_TOLERANCE_DAYS,
} from './utils/planLedger'
import {
  getCardName,
  isSameMonth,
  isBillableTransaction,
  isCreditCardPayment,
  isInstallmentConversionCredit,
  matchesCard,
  normalizeFinanceData,
  parseISODate,
  installmentAmountNotRecordedInWindow,
  planAmountNotRecorded,
  resolveCardId,
  toISODate,
  transactionCycleDate,
  ymd,
} from './utils/financeData'

/* eslint-disable react-hooks/set-state-in-effect */

const STORAGE_KEY = 'cardnest_v1'

function endOfMonth(date) {
  return new Date(date.getFullYear(), date.getMonth() + 1, 0)
}

function loadStorage() {
  try {
    const raw = localStorage.getItem(STORAGE_KEY)
    return raw ? normalizeFinanceData(JSON.parse(raw)) : null
  } catch {
    return null
  }
}

const MONTH_NAMES = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']
const WEEKDAY_NAMES = ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat']
const CATEGORY_COLORS = {}

function getGreeting(hour) {
  if (hour < 5) return '夜深'
  if (hour < 11) return '早安'
  if (hour < 13) return '午安'
  if (hour < 18) return '午後好'
  return '晚安'
}

// 瘥?撟曇???狡嚗像甈曄??券?嚗鞈???billingDay嚗?鞈?敺?nextDate 摮葡?典???
function billingDayOf(plan) {
  return plan.billingDay ?? dayFromMD(plan.nextDate) ?? 1
}
// 訂閱／分期的「下次扣款日」「已繳幾期」都改成對 transactions 做即時查詢
// （見 utils/planLedger.js），不再是 plan 自己手動維護的一份旗標。
// pendingConfirmCount：已經材料化但銀行還沒確認過的期別數，讓「已入帳、待對帳」
// 這個新狀態在畫面上看得見，不是白算。
function enrichPlans(plans, transactions) {
  const today = new Date()
  return plans.map(p => {
    const pendingConfirmCount = transactions.filter(
      tx => tx.planId === p.id && tx.autoGenerated && !tx.postedDate
    ).length

    if (p.type === 'installment') {
      const paidCount = installmentPaidCount(p, transactions)
      const due = duePlanOccurrences(p, transactions, { today })
      const next = due[0] ?? nextDueOccurrence(p, transactions, { today })
      const unpaidOccurrences = due.length > 0 ? due : (next ? [next] : [])
      if (!next) {
        // 已經繳清所有期數：不會再有下一期，維持已知的欄位就好
        return { ...p, paidCount, unpaidOccurrences, pendingConfirmCount }
      }
      const daysLeft = daysUntilPlanDue(next)
      return {
        ...p,
        paidCount,
        nextDate: `${Number(next.dueDate.slice(5, 7))}/${Number(next.dueDate.slice(8, 10))}`,
        daysLeft,
        status: statusForDaysLeft(daysLeft),
        unpaidOccurrences,
        pendingConfirmCount,
      }
    }
    const billingDay = billingDayOf(p)
    const next = nextOccurrence(billingDay)
    const daysLeft = daysUntil(next)
    return { ...p, billingDay, nextDate: formatMD(next), daysLeft, status: statusForDaysLeft(daysLeft), pendingConfirmCount }
  })
}

// 撱箇??祇梧??望韏瑞?嚗?憭拍???狡銵???鈭辣隞亙???脫?蝷?
function buildWeekDays(plans, cards, transactions) {
  const colorByCard = {}
  const colorByCardId = {}
  cards.forEach(c => { colorByCard[c.name] = c.color })
  cards.forEach(c => { colorByCardId[c.id] = c.color })

  const today = new Date()
  today.setHours(0, 0, 0, 0)
  const weekStart = new Date(today)
  weekStart.setDate(today.getDate() - today.getDay()) // ?望
  const weekEnd = new Date(weekStart)
  weekEnd.setDate(weekStart.getDate() + 7)

  const days = Array.from({ length: 7 }, (_, i) => {
    const date = new Date(weekStart)
    date.setDate(weekStart.getDate() + i)
    return { date, isToday: date.getTime() === today.getTime(), events: [] }
  })

  plans.forEach(p => {
    const stillActive = p.type === 'subscription'
      ? (p.active ?? true)
      : (installmentPaidCount(p, transactions) < p.totalCount)
    if (!stillActive) return
    const dt = nextOccurrence(billingDayOf(p))
    dt.setHours(0, 0, 0, 0)
    if (dt < weekStart || dt >= weekEnd) return
    const idx = Math.round((dt - weekStart) / 86400000)
    days[idx].events.push({
      id: p.id,
      name: p.name,
      card: getCardName(p, cards),
      amount: p.amount,
      color: colorByCardId[resolveCardId(p, cards)] ?? colorByCard[p.card] ?? '#A98274',
    })
  })

  return days
}

// ?瑕閮???date ??"M/D" 憿舐內摮葡嚗??僑隞踝?嚗??曉瘥??遢?喳?斗?臭??舀??
function isThisMonth(displayDate, from = new Date()) {
  return isSameMonth(displayDate, from)
}

// ???僑隞賜? "M/D" ???? near ??亥????湔???踹?頝典僑隤文嚗?憒?12 ?董?桅望?頝典 1 ??
function resolveNearDate(displayDate, near) {
  return parseISODate(displayDate, near)
}

// 靘?撣單???箇???典董?桅望?????銝活蝯董?伐??祆?撣喳?芣迫暺???銝活蝯董?伐?銝?撣喳韏琿?嚗?
function billingCycleBounds(billingDay, today) {
  if (!billingDay) return null
  const y = today.getFullYear(), m = today.getMonth(), d = today.getDate()
  const lastBillingDate = d >= billingDay ? new Date(y, m, billingDay) : new Date(y, m - 1, billingDay)
  const prevBillingDate = new Date(lastBillingDate.getFullYear(), lastBillingDate.getMonth() - 1, billingDay)
  return { prevBillingDate, lastBillingDate }
}

function computeDashboard(transactions, cards, fixedMonthlyAmount = 0, envelopes = [], plans = []) {
  // ??嚗?蝜喳????瑕閮?嚗楊????????頝臬?銝敞??
  const monthTx = transactions.filter(tx => Number(tx.amount) > 0 && isThisMonth(tx.date))
  const totalSpent = monthTx.reduce((s, tx) => s + tx.amount, 0)
  const totalBudget = cards.reduce((s, c) => s + c.budget, 0)
  // ?祆??臬 = 撌脰????+ 閮嚗???擐?嚗?∠???銝敹像皜嚗?
  const monthlyOut = totalSpent + fixedMonthlyAmount
  const remaining = Math.max(0, totalBudget - monthlyOut)
  const pct = totalBudget > 0 ? monthlyOut / totalBudget : 0
  const status = pct < 0.7 ? 'safe' : pct < 0.9 ? 'warning' : 'danger'
  const monthName = MONTH_NAMES[new Date().getMonth()]

  const today = new Date()
  const enrichedCards = cards.map(card => {
    const allCardTx = transactions.filter(tx => matchesCard(tx, card))
    const cardTx = allCardTx.filter(isBillableTransaction)
    const bounds = billingCycleBounds(card.billingDay, today)
    // 銝?嚗歇蝯董嚗?敺像甈橘?嚗?敞蝛?蝯董?乩?敺?瑞?嚗?瘝撣喉?嚗?蝯董?亙?嚗??舀??
    let used, currentCycleAmount
    if (bounds) {
      used = cardTx
        .filter(tx => { const dt = resolveNearDate(transactionCycleDate(tx), today); return dt && dt > bounds.prevBillingDate && dt <= bounds.lastBillingDate })
        .reduce((s, tx) => s + tx.amount, 0)
      currentCycleAmount = cardTx
        .filter(tx => { const dt = resolveNearDate(transactionCycleDate(tx), today); return dt && dt > bounds.lastBillingDate && dt <= today })
        .reduce((s, tx) => s + tx.amount, 0)
    } else {
      // 瘝‵蝯董?伐?????祆??隡啁?
      used = cardTx.filter(tx => isThisMonth(tx.date)).reduce((s, tx) => s + tx.amount, 0)
      currentCycleAmount = 0
    }
    // ???脰?銝剔?閮嚗???蝯艾?敞蝛?蝝啣??嚗?撣喳?望?甇瑕閮??臬隞嗡?嚗?
    const subsOnCard = plans
      .filter(p => p.type === 'subscription' && (p.active ?? true) && matchesCard(p, card))
      .reduce((s, p) => s + planAmountNotRecorded({
        plan: p,
        transactions,
        cards,
        windowStart: bounds?.lastBillingDate ?? new Date(today.getFullYear(), today.getMonth(), 1),
        windowEnd: today,
      }), 0)
    const monthEnd = endOfMonth(today)
    const instOnCard = plans
      .filter(p => p.type === 'installment' && matchesCard(p, card) && installmentPaidCount(p, transactions) < p.totalCount)
      .reduce((s, p) => s + installmentAmountNotRecordedInWindow({
        plan: p,
        transactions,
        cards,
        windowStart: bounds?.lastBillingDate ?? new Date(today.getFullYear(), today.getMonth(), 1),
        windowEnd: monthEnd,
      }), 0)
    const cardRemaining = card.budget - used
    const cp = card.budget > 0 ? used / card.budget : 0
    const cardStatus = cp < 0.7 ? 'safe' : cp < 0.9 ? 'warning' : 'danger'

    // 撣喳?望?嚗?銝??舀??祕?交??蝡????芰像??銝?渡敞??銝??????憭望?鋡怨炊??
    const unpaid = unpaidCycles(card)
    const unpaidTotal = totalUnpaid(card)
    const unpaidWithDaysLeft = unpaid.map(c => ({ ...c, daysLeft: daysUntilDue(c) }))
    const postedDateCount = allCardTx.filter(tx => tx.postedDate && tx.postedDate !== tx.date).length
    const paymentCount = allCardTx.filter(isCreditCardPayment).length
    const installmentCreditCount = allCardTx.filter(isInstallmentConversionCredit).length
    const reconciliationHints = [
      postedDateCount > 0 && `${postedDateCount} 筆使用入帳日歸帳`,
      paymentCount > 0 && `${paymentCount} 筆繳款未列入消費`,
      installmentCreditCount > 0 && `${installmentCreditCount} 筆分期沖帳未列入消費`,
    ].filter(Boolean)

    // ?箏?憿舐內??甈∠?撣喉?蝜單狡?伐??湔敺?身摰蝞?銝?鞈湔?瘝??芰像撣喳嚗?
    // 撠梁???????0 銋?敺?撐?⊥?????撣喋???蝜喋?
    const nextClose = nextOccurrence(Number(card.billingDay) || 1)
    const nextDue = new Date(nextClose)
    nextDue.setDate(nextDue.getDate() + (Number(card.dueDay) || 0))

    return {
      ...card, used, currentCycleAmount,
      subsOnCard, instOnCard,
      unpaidCycles: unpaidWithDaysLeft, unpaidTotal,
      reconciliationHints,
      nextCloseLabel: formatMD(nextClose),
      nextDueLabel: formatMD(nextDue),
      status: cardStatus,
      statusText: cardStatus === 'safe'
        ? `Remaining NT$${cardRemaining.toLocaleString()}`
        : cardStatus === 'warning' ? 'Approaching budget'
        : 'Over budget',
    }
  })

  const catMap = {}
  monthTx.forEach(tx => { catMap[tx.category] = (catMap[tx.category] ?? 0) + tx.amount })
  const categories = Object.entries(catMap)
    .map(([name, amount]) => ({
      name, amount,
      percent: totalSpent > 0 ? Math.round(amount / totalSpent * 100) : 0,
      color: CATEGORY_COLORS[name] ?? '#B9ADA6',
    }))
    .sort((a, b) => b.amount - a.amount)

  // ??靽∪???嚗??縑撠??祆?撌脰嚗?瑕???蜇嚗?瘥?憿漲
  const envelopeView = envelopes.map(e => {
    const used = catMap[e.name] ?? 0
    return {
      id: e.id,
      name: e.name,
      necessity: e.necessity,
      budget: e.monthlyBudget,
      used,
      remaining: e.monthlyBudget - used,
      color: CATEGORY_COLORS[e.name] ?? '#B9ADA6',
    }
  })
  const envelopeSummary = {
    necessaryBudget: envelopes.filter(e => e.necessity === 'necessary').reduce((s, e) => s + e.monthlyBudget, 0),
    flexibleBudget: envelopes.filter(e => e.necessity === 'flexible').reduce((s, e) => s + e.monthlyBudget, 0),
    necessaryUsed: envelopeView.filter(e => e.necessity === 'necessary').reduce((s, e) => s + e.used, 0),
    flexibleUsed: envelopeView.filter(e => e.necessity === 'flexible').reduce((s, e) => s + e.used, 0),
  }

  const trendMap = monthTx.reduce((map, tx) => {
    const date = parseISODate(tx.date, today)
    if (!date) return map
    const key = `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, '0')}`
    map.set(key, (map.get(key) ?? 0) + Number(tx.amount || 0))
    return map
  }, new Map())
  const trends = [...trendMap.entries()]
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([key, amount]) => {
      const [, month] = key.split('-')
      return { month: `${Number(month)}/${today.getFullYear()}`, amount }
    })

  const estimatedTotal = totalSpent + fixedMonthlyAmount
  const currentMonth = {
    name: monthName,
    total: totalSpent,
    budget: totalBudget,
    remaining,
    fixedMonthlyAmount,
    estimatedTotal,
    status,
    statusText: status === 'safe' ? `${monthName} on track` : status === 'warning' ? `${monthName} near budget` : `${monthName} over budget`,
  }

  return { currentMonth, enrichedCards, categories, trends, envelopeView, envelopeSummary }
}

export default function App() {
  const stored = loadStorage()

  // 敹像皜?????蝵柴?頝冽?????????格敺拍?芰像
  const currentMonthKey = `${new Date().getFullYear()}-${new Date().getMonth()}`
  const storedChecklist = stored?.checklist ?? []
  const initialChecklist = stored?.checklistMonth === currentMonthKey
    ? storedChecklist
    : storedChecklist.map(i => ({ ...i, done: false }))

  const [tab, setTab] = useState('dashboard')
  const [toast, setToast] = useState(null) // { message, onUndo? }
  const toastTimer = useRef(null)
  const autoSyncAttempted = useRef(false)
  const [cards, setCards] = useState(stored?.cards ?? [])
  const [plans, setPlans] = useState(stored?.plans ?? [])
  const [transactions, setTransactions] = useState(stored?.transactions ?? [])
  const [fxSettings, setFxSettings] = useState(stored?.fxSettings ?? { usdRate: 32.5, feeRate: 1.5 })
  const [checklist, setChecklist] = useState(initialChecklist)
  const [checklistMonth] = useState(currentMonthKey)
  const [envelopes, setEnvelopes] = useState(stored?.envelopes ?? [])
  const [income, setIncome] = useState(stored?.income ?? 0)
  const [savings, setSavings] = useState(stored?.savings ?? [])
  const [googleSync, setGoogleSync] = useState(stored?.googleSync ?? null)
  const [cardImport, setCardImport] = useState(
    stored?.cardImport ?? { sheetId: '', bankCardMap: {}, importedKeys: [] }
  )
  const [importingCardNotifications, setImportingCardNotifications] = useState(false)

  useEffect(() => {
    localStorage.setItem(STORAGE_KEY, JSON.stringify({ cards, plans, transactions, fxSettings, checklist, checklistMonth, envelopes, income, savings, googleSync, cardImport }))
  }, [cards, plans, transactions, fxSettings, checklist, checklistMonth, envelopes, income, savings, googleSync, cardImport])

  // 鋆?瘥撐?∠?撣喳?望?嚗?∠???頝銝活??撌脩?頝券??啁?蝯董?伐??賣??券ㄐ?芸???
  // ?啁?銝???蒂撖怠? cards?歇蝬??函??望?銝?鋡怠??堆??芰像??銝?渡?????憭晞?
  useEffect(() => {
    setCards((prev) => {
      let changed = false
      const next = prev.map((card) => {
        const cycles = ensureBillingCycles(card, { transactions, plans })
        if (cycles.length !== (card.billingCycles?.length ?? 0)) {
          changed = true
          return { ...card, billingCycles: cycles }
        }
        return card
      })
      return changed ? next : prev
    })
  }, [cards, transactions, plans])

  // 瘥?靽∠?⊿?隡啣董?殷???閬???瘥撐?∠策銝??憭扳?閬像憭????詨?嚗?
  // ?湔?蝛拙?銝?嚗????箸?瘝?撠董??閮歇蝜唾蕭擃蕭雿??楊???身撣嗅
  // 銝??祕??撣喟???嚗雿絲憪摯閮?Chia ?臭誑?典?蝜喲???隤踵??
  useEffect(() => {
    setCards((prev) => {
      let changed = false
      const next = prev.map((card) => {
        if (card.estimatedBillMonth === currentMonthKey) return card
        changed = true
        const cycles = card.billingCycles ?? []
        const lastClosed = [...cycles].sort((a, b) => a.cycleKey.localeCompare(b.cycleKey)).pop()
        return { ...card, estimatedBill: lastClosed?.amount ?? 0, estimatedBillMonth: currentMonthKey }
      })
      return changed ? next : prev
    })
  }, [cards, currentMonthKey])

  // 每次計畫／交易／卡片有變動，就檢查每個計畫有沒有已經到期、但還沒變成
  // 真實刷卡記錄的期別——有的話直接材料化補上，讓「這期真的花了多少」永遠
  // 對得起來，不管是分期還是訂閱。
  // 材料化的判斷要放在 setTransactions 的更新函式裡、對著 prev 算，不能對著
  // 外層 closure 抓到的 transactions 算——StrictMode 開發模式下 effect 會連續
  // 呼叫兩次，兩次都還沒看到彼此的更新結果，各自對同一份舊 transactions 生出
  // 一批全新 id 的交易，就會重複材料化兩份。對著 prev 算就天生冪等：先跑的那次
  // 把新交易寫進去後，後跑的那次拿到的 prev 已經包含它，查詢自然回傳空陣列。
  useEffect(() => {
    setTransactions((prev) => {
      const { newTransactions } = materializeDuePlanTransactions({ plans, transactions: prev, cards, today: new Date() })
      return newTransactions.length > 0 ? [...newTransactions, ...prev] : prev
    })
  }, [plans, transactions, cards])

  const showToast = useCallback((message) => {
    if (toastTimer.current) clearTimeout(toastTimer.current)
    setToast({ message })
    toastTimer.current = setTimeout(() => setToast(null), 2800)
  }, [])

  const showUndoToast = useCallback((message, onUndo) => {
    if (toastTimer.current) clearTimeout(toastTimer.current)
    setToast({ message, onUndo })
    toastTimer.current = setTimeout(() => setToast(null), 5000)
  }, [])

  // Plans handlers
  const normalizePlan = useCallback((plan) => {
    const cardId = resolveCardId(plan, cards)
    const card = cards.find(c => c.id === cardId)
    return {
      ...plan,
      ...(cardId && { cardId }),
      card: plan.card ?? card?.name ?? '',
    }
  }, [cards])
  const handleAddPlan = useCallback((plan) => setPlans(p => [normalizePlan(plan), ...p]), [normalizePlan])
  const handleUpdatePlan = useCallback((updated) => setPlans(p => p.map(pl => pl.id === updated.id ? normalizePlan(updated) : pl)), [normalizePlan])
  // 從刷卡記錄「設為訂閱」：跟轉分期不同，這筆刷卡記錄要保留（本期已扣款的真實紀錄），
  // 只新增一個訂閱計畫追蹤之後的扣款。同卡同名的訂閱已經存在就不重複建立，
  // 避免每次匯入格式對不上、使用者又手動點一次時越疊越多筆
  const handleMarkAsSubscription = useCallback((plan) => {
    const isDuplicate = plans.some((p) => (
      p.type === 'subscription'
      && (p.active ?? true)
      && matchesCard(p, { id: plan.cardId, name: plan.card })
      && String(p.name).trim().toLowerCase() === String(plan.name).trim().toLowerCase()
    ))
    if (isDuplicate) {
      showToast(`已經有「${plan.name}」的訂閱計畫了，這筆記錄視為本期扣款，不重複建立`)
      return
    }
    handleAddPlan(plan)
    showToast(`已設為訂閱，「${plan.name}」之後的扣款會自動對應`)
  }, [plans, handleAddPlan, showToast])
  const handleDeletePlan = useCallback((id) => {
    setPlans(prev => {
      const idx = prev.findIndex(x => x.id === id)
      const item = prev[idx]
      const next = prev.filter(x => x.id !== id)
      showUndoToast(`Deleted ${item.name}`, () => {
        setPlans(p => {
          const r = [...p]
          r.splice(Math.min(idx, r.length), 0, item)
          return r
        })
      })
      return next
    })
  }, [showUndoToast])
  // 分期「標記已繳」現在操作的是 transactions，不是 plan 自己的旗標：
  // 1) 有材料化但還沒確認的交易，就確認最早那一筆（等同對帳）。
  // 2) 沒有待確認的，代表使用者要提前繳下一期——直接材料化一筆並標記已確認。
  // 3) 兩者都沒有，代表要復原：把最近一筆已確認的材料化交易取消確認標記
  //    （這筆刷卡記錄本身不刪除，錢已經真實花掉是事實）。
  // 訂閱從來沒有在畫面上接過這顆按鈕（PlanCard 只有分期分支才有 onMarkPaid），
  // 所以這裡不用再處理訂閱的情況。
  const handleMarkPaid = useCallback((id) => {
    const plan = plans.find(p => p.id === id)
    if (!plan || plan.type !== 'installment') return
    const today = new Date()
    const todayStr = ymd(today)

    const pendingTx = transactions
      .filter(tx => tx.planId === id && tx.autoGenerated && !tx.postedDate)
      .sort((a, b) => a.date.localeCompare(b.date))
    if (pendingTx.length > 0) {
      const targetId = pendingTx[0].id
      setTransactions(prev => prev.map(t => t.id === targetId ? { ...t, postedDate: todayStr } : t))
      return
    }

    const next = nextDueOccurrence(plan, transactions, { today })
    if (next) {
      const newTx = {
        id: crypto.randomUUID(),
        planId: id,
        planCycleKey: next.cycleKey,
        autoGenerated: true,
        name: plan.name,
        category: '分期',
        cardId: resolveCardId(plan, cards),
        card: plan.card,
        amount: plan.amount,
        date: next.dueDate,
        note: '',
        postedDate: todayStr,
      }
      setTransactions(prev => [newTx, ...prev])
      return
    }

    const confirmedTx = transactions
      .filter(tx => tx.planId === id && tx.autoGenerated && tx.postedDate)
      .sort((a, b) => b.date.localeCompare(a.date))
    if (confirmedTx.length === 0) return
    const undoId = confirmedTx[0].id
    setTransactions(prev => prev.map(t => {
      if (t.id !== undoId) return t
      const { postedDate, ...rest } = t
      return rest
    }))
  }, [plans, transactions, cards])

  // Transactions handlers
  const normalizeTransaction = useCallback((tx) => {
    const cardId = resolveCardId(tx, cards)
    const card = cards.find(c => c.id === cardId)
    return {
      ...tx,
      ...(cardId && { cardId }),
      card: tx.card ?? card?.name ?? '',
      date: toISODate(tx.date),
    }
  }, [cards])
  const handleAddTransaction = useCallback((tx) => setTransactions(p => [normalizeTransaction(tx), ...p]), [normalizeTransaction])
  const handleUpdateTransaction = useCallback((updated) => setTransactions(p => p.map(t => t.id === updated.id ? normalizeTransaction(updated) : t)), [normalizeTransaction])
  // ?桃??瑕頧????啣???閮銝衣宏?文??祉??桃?閮?嚗??銴??交???
  const handleConvertToInstallment = useCallback((txId, plan) => {
    setPlans(p => [normalizePlan(plan), ...p])
    setTransactions(p => p.filter(t => t.id !== txId))
  }, [normalizePlan])

  // 匯入新的刷卡記錄／更新既有記錄（跟訂閱／分期材料化交易對帳時會需要更新
  // 既有那一筆，而不是插入新的一筆）。permalink 去重仍然在 Settings 那邊處理。
  const handleImportTransactions = useCallback((newTxs, newKeys, summary = {}) => {
    const updates = summary.updates ?? {}
    setTransactions(p => {
      const withUpdates = Object.keys(updates).length > 0
        ? p.map(t => updates[t.id] ? { ...t, ...updates[t.id] } : t)
        : p
      return [...newTxs.map(normalizeTransaction), ...withUpdates]
    })
    setCardImport(prev => ({
      ...prev,
      importedKeys: [...prev.importedKeys, ...newKeys],
      lastImportAt: Date.now(),
      lastImportCount: newTxs.length,
      lastImportDuplicateCount: summary.duplicateCount ?? 0,
      lastImportSkippedUnmapped: summary.skippedUnmapped ?? 0,
    }))
  }, [normalizeTransaction])

  const handleImportCardNotifications = useCallback(async () => {
    const clientId = googleSync?.clientId?.trim()
    const importSheetId = cardImport?.sheetId?.trim()
    if (!clientId || !importSheetId) {
      showToast('請先到設定填 Google Client ID 和消費記錄 Sheet ID')
      return
    }
    setImportingCardNotifications(true)
    try {
      const token = await getAccessToken(clientId)
      const rows = await fetchImportRows({ accessToken: token, sheetId: importSheetId })
      const importedKeys = new Set(cardImport?.importedKeys ?? [])

      // 已經材料化、但還沒被銀行確認過的訂閱／分期交易，是這次匯入優先要
      // 「認領」的對象：用卡片＋到期日容忍範圍比對，不比對金額或名稱——那正是
      // 舊機制會重複計算的脆弱判斷。一筆只能被一次匯入認領一次，避免同一期
      // 被兩筆銀行資料重複兌現。
      const claimed = new Set()
      const toleranceMs = IMPORT_MATCH_TOLERANCE_DAYS * 86400000
      const findCandidate = (mappedCard, rawDate) => {
        const rawDt = parseISODate(toImportISODate(rawDate))
        if (!rawDt) return []
        return transactions.filter((tx) => {
          if (!tx.planId || !tx.autoGenerated || tx.postedDate || claimed.has(tx.id)) return false
          if (!matchesCard(tx, mappedCard)) return false
          const txDt = parseISODate(tx.date)
          return txDt && Math.abs(txDt - rawDt) <= toleranceMs
        })
      }

      const newTxs = []
      const newKeys = []
      const updates = {}
      const amountDrifts = []
      let skippedUnmapped = 0
      let duplicateCount = 0
      let reconciledCount = 0

      rows.forEach((row) => {
        if (importedKeys.has(row.permalink)) {
          duplicateCount++
          return
        }
        const mappedCard = cards.find((card) => card.id === cardImport?.bankCardMap?.[row.bank] || card.name === cardImport?.bankCardMap?.[row.bank])
        if (!mappedCard) { skippedUnmapped++; return }

        const candidates = findCandidate(mappedCard, row.rawDate)
        if (candidates.length === 1) {
          const target = candidates[0]
          claimed.add(target.id)
          if (Math.abs(Number(row.amount) - Number(target.amount)) > 0.5) {
            amountDrifts.push({ name: target.name, oldAmount: Number(target.amount), newAmount: Number(row.amount) })
          }
          updates[target.id] = {
            amount: row.amount,
            date: toImportISODate(row.rawDate),
            postedDate: row.rawPostedDate ? toImportISODate(row.rawPostedDate) : toImportISODate(row.rawDate),
            name: row.merchant || target.name,
          }
          newKeys.push(row.permalink)
          reconciledCount++
          return
        }

        newTxs.push({
          id: crypto.randomUUID(),
          name: row.merchant || row.bank,
          category: row.transactionType || '其他',
          cardId: mappedCard.id,
          card: mappedCard.name,
          amount: row.amount,
          date: toImportISODate(row.rawDate),
          ...(row.rawPostedDate && { postedDate: toImportISODate(row.rawPostedDate) }),
          note: `自動匯入・${row.bank}`,
        })
        newKeys.push(row.permalink)
      })

      handleImportTransactions(newTxs, newKeys, { duplicateCount, skippedUnmapped, updates })

      const driftMsg = amountDrifts.length > 0
        ? `；${amountDrifts.map(d => `${d.name} 金額從 NT$${d.oldAmount} 變成 NT$${d.newAmount}`).join('、')}`
        : ''
      const reconciledMsg = reconciledCount > 0 ? `，對帳 ${reconciledCount} 筆` : ''
      if (skippedUnmapped > 0) {
        showToast(`新增 ${newTxs.length} 筆${reconciledMsg}，重複 ${duplicateCount} 筆，${skippedUnmapped} 筆未對應卡片${driftMsg}`)
      } else {
        showToast(`新增 ${newTxs.length} 筆${reconciledMsg}，重複略過 ${duplicateCount} 筆${driftMsg}`)
      }
    } catch (e) {
      showToast(e.message || '更新失敗，請稍後再試')
    } finally {
      setImportingCardNotifications(false)
    }
  }, [cardImport, cards, googleSync, transactions, handleImportTransactions, showToast])

  const handleDeleteTransaction = useCallback((id) => {
    setTransactions(prev => {
      const idx = prev.findIndex(x => x.id === id)
      const item = prev[idx]
      const next = prev.filter(x => x.id !== id)
      showUndoToast(`Deleted ${item.name}`, () => {
        setTransactions(p => {
          const r = [...p]
          r.splice(Math.min(idx, r.length), 0, item)
          return r
        })
      })
      return next
    })
  }, [showUndoToast])

  // Checklist handlers嚗???蝜單??殷?
  const handleAddChecklistItem = useCallback((item) => setChecklist(p => [...p, item]), [])
  const handleUpdateChecklistItem = useCallback((updated) => setChecklist(p => p.map(i => i.id === updated.id ? updated : i)), [])
  const handleDeleteChecklistItem = useCallback((id) => setChecklist(p => p.filter(i => i.id !== id)), [])

  // ?暸敹像?嚗??董?園??甇日??殷??嗆??暸嚗??銝祕??憿??亙董?塚???嚗??蝑?
  const handleToggleChecklistItem = useCallback((id) => {
    const item = checklist.find(i => i.id === id)
    const nowDone = item ? !item.done : false
    setChecklist(prev => prev.map(i => i.id === id ? { ...i, done: !i.done } : i))
    if (!item) return
    const amt = Number(item.amount)
    const dateStr = `${new Date().getMonth() + 1}/${new Date().getDate()}`
    setSavings(prev => prev.map(g => {
      if (g.linkedChecklistId !== id) return g
      const entries = g.entries ?? []
      const monthEntry = entries.find(e => e.type === 'in' && e.month === checklistMonth && e.source === 'checklist')
      if (nowDone) {
        if (monthEntry) return g // ??撌脣??伐?銝?銴?
        const entry = { id: crypto.randomUUID(), type: 'in', amount: amt, date: dateStr, note: '?祆??亙', month: checklistMonth, source: 'checklist' }
        return { ...g, saved: Number(g.saved) + amt, entries: [...entries, entry] }
      }
      if (!monthEntry) return g // ???祆??亙
      return { ...g, saved: Number(g.saved) - Number(monthEntry.amount), entries: entries.filter(e => e.id !== monthEntry.id) }
    }))
  }, [checklist, checklistMonth])

  // ?脰?撣單
  const handleAddSaving = useCallback((goal) => setSavings(p => [...p, { entries: [], ...goal }]), [])
  const handleUpdateSaving = useCallback((updated) => setSavings(p => p.map(g => g.id === updated.id ? { ...g, ...updated } : g)), [])
  const handleDeleteSaving = useCallback((id) => setSavings(p => p.filter(g => g.id !== id)), [])
  // ???亙嚗????董?嗥嚗?
  const handleContributeSaving = useCallback((id) => setSavings(p => p.map(g => {
    if (g.id !== id) return g
    const amt = Number(g.monthly)
    const dateStr = `${new Date().getMonth() + 1}/${new Date().getDate()}`
    const entry = { id: crypto.randomUUID(), type: 'in', amount: amt, date: dateStr, note: '???亙', source: 'manual' }
    return { ...g, saved: Number(g.saved) + amt, entries: [...(g.entries ?? []), entry] }
  })), [])
  // 撣單?臬嚗祕???Ｚ??靘?蝜喳飛鞎鳴?
  const handleSpendSaving = useCallback((id, amount, note) => setSavings(p => p.map(g => {
    if (g.id !== id) return g
    const amt = Number(amount)
    const dateStr = `${new Date().getMonth() + 1}/${new Date().getDate()}`
    const entry = { id: crypto.randomUUID(), type: 'out', amount: amt, date: dateStr, note: note || '?臬', source: 'manual' }
    return { ...g, saved: Number(g.saved) - amt, entries: [...(g.entries ?? []), entry] }
  })), [])
  // ??券嚗飛?塚?閮?銝蝑?綽?
  const handleResetSaving = useCallback((id) => setSavings(p => p.map(g => {
    if (g.id !== id) return g
    const amt = Number(g.saved)
    if (amt <= 0) return g
    const dateStr = `${new Date().getMonth() + 1}/${new Date().getDate()}`
    const entry = { id: crypto.randomUUID(), type: 'out', amount: amt, date: dateStr, note: '??券', source: 'manual' }
    return { ...g, saved: 0, entries: [...(g.entries ?? []), entry] }
  })), [])

  // Envelope handlers嚗?憿縑撠?蝞?
  const handleAddEnvelope = useCallback((env) => setEnvelopes(p => [...p, env]), [])
  const handleUpdateEnvelope = useCallback((updated) => setEnvelopes(p => p.map(e => e.id === updated.id ? updated : e)), [])
  const handleDeleteEnvelope = useCallback((id) => setEnvelopes(p => p.filter(e => e.id !== id)), [])

  // Cards handlers
  const handleAddCard = useCallback((card) => setCards(p => [...p, card]), [])
  const handleSaveCard = useCallback((updated) => setCards(p => p.map(c => c.id === updated.id ? updated : c)), [])
  const handleDeleteCard = useCallback((id) => setCards(p => p.filter(c => c.id !== id)), [])
  // 璅????董?桀歇蝜喉?cycleId ?典??臭?嚗?交?箏????∠?頝銝???
  // ?舫???????董?嗆甈?
  const handleMarkCardPaid = useCallback((cycleId, opts = {}) => {
    const paidAt = `${new Date().getFullYear()}-${String(new Date().getMonth() + 1).padStart(2, '0')}-${String(new Date().getDate()).padStart(2, '0')}`
    setCards(prev => prev.map(c => {
      if (!c.billingCycles?.some(cy => cy.id === cycleId)) return c
      return {
        ...c,
        billingCycles: c.billingCycles.map(cy => cy.id === cycleId ? { ...cy, paid: true, paidAt } : cy),
      }
    }))
    if (opts.fromSavingId && Number(opts.amount) > 0) {
      handleSpendSaving(opts.fromSavingId, Number(opts.amount), 'Card payment')
    }
  }, [handleSpendSaving])

  // 銝甈⊥??撐?⊥??蝜喟???賣?閮歇蝜喉?靘?鋆像憟賢嗾??甈?撣喳嚗?
  const handleMarkAllCyclesPaid = useCallback((cardId) => {
    const paidAt = `${new Date().getFullYear()}-${String(new Date().getMonth() + 1).padStart(2, '0')}-${String(new Date().getDate()).padStart(2, '0')}`
    setCards(prev => prev.map(c => {
      if (c.id !== cardId) return c
      return {
        ...c,
        billingCycles: (c.billingCycles ?? []).map(cy => cy.paid ? cy : { ...cy, paid: true, paidAt }),
      }
    }))
  }, [])

  // ???寞?銝???唳??伐?撱嗅?蝜單狡嚗??楊頛舫?憿??銵祕?董?株?隡啁?銝???
  const handleUpdateCycle = useCallback((cardId, cycleId, fields) => {
    setCards(prev => prev.map(c => {
      if (c.id !== cardId) return c
      return {
        ...c,
        billingCycles: applyCycleUpdate(c.billingCycles ?? [], cycleId, fields),
      }
    }))
  }, [])

  // ??隤踵???縑?典?摯撣喳??嚗????嚗?帘摰?銝?撠董/撌脩像??蔣?選?
  const handleUpdateEstimatedBill = useCallback((cardId, amount) => {
    setCards(prev => prev.map(c => c.id === cardId ? { ...c, estimatedBill: Number(amount) || 0 } : c))
  }, [])

  const handleClearData = useCallback(() => {
    localStorage.removeItem(STORAGE_KEY)
    setCards([])
    setPlans([])
    setTransactions([])
    setChecklist([])
    setEnvelopes([])
    setIncome(0)
    setSavings([])
    setFxSettings({ usdRate: 32.5, feeRate: 1.5 })
    setGoogleSync(null)
    setTab('dashboard')
  }, [])

  // ???遢嚗?臬????寡???
  const handleImportData = useCallback((data) => {
    if (!data || typeof data !== 'object') return false
    const normalized = normalizeFinanceData(data)
    setCards(normalized.cards)
    setPlans(normalized.plans)
    setTransactions(normalized.transactions)
    setChecklist(Array.isArray(data.checklist) ? data.checklist : [])
    setEnvelopes(Array.isArray(data.envelopes) ? data.envelopes : [])
    if (data.fxSettings && typeof data.fxSettings === 'object') setFxSettings(data.fxSettings)
    if (typeof data.income === 'number') setIncome(data.income)
    setSavings(Array.isArray(data.savings) ? data.savings : [])
    setGoogleSync(data.googleSync ?? null)
    setCardImport(data.cardImport ?? { sheetId: '', bankCardMap: {}, importedKeys: [] })
    return true
  }, [])

  // 擐?嚗?∠????祆??臬?摰?? ?????+ ?芰像皜???瘥?嚗?銝敹像皜
  const fixedMonthStart = new Date(new Date().getFullYear(), new Date().getMonth(), 1)
  const fixedMonthEnd = endOfMonth(new Date())
  const fixedMonthlyAmount = plans
    .filter(p => p.type === 'subscription' ? (p.active ?? true) : (installmentPaidCount(p, transactions) < p.totalCount))
    .reduce((s, p) => {
      const occ = upcomingUnmaterializedInWindow(p, transactions, { windowStart: fixedMonthStart, windowEnd: fixedMonthEnd })
      return s + occ.length * Number(p.amount)
    }, 0)

  // 敹??臬 / ?暑??
  // ?芰??歇?暸??敹像?嚗?訾誨銵券?撌脩?蝣箏????Ｙ?銝?嚗?
  // ?芸?貊??閬??挾嚗?閰脫????脣?閬?箇蜇憿?
  const checklistTotal = checklist.filter(i => i.done).reduce((s, i) => s + Number(i.amount), 0)
  // ???敹像??????撌脣敹像皜鋆∴?銝?銴??乓?
  // ?芣?????銝?賊?憭???撣單嚗??舀?乩?憭憭????脣?閬?箝?
  const savingsMonthly = savings.reduce((s, g) => s + Number(g.monthly || 0), 0)
  const essentialSavings = savings
    .filter(g => !g.linkedChecklistId && g.countInEssential)
    .reduce((s, g) => s + Number(g.monthly || 0), 0)
  const essentialTotal = checklistTotal + essentialSavings

  const { currentMonth, enrichedCards, categories, trends, envelopeView, envelopeSummary } = computeDashboard(transactions, cards, fixedMonthlyAmount, envelopes, plans)

  // 靽∠?⊿?隡啣董?殷???閬??身摰??詨?嚗?帘摰?霈?銝?撠董嚗歇蝜喟??蔣?踱?
  // ???撌脩??望?撠望?望?鈭?銝??璅?撌脩像撠晞????暑蝯???
  const cardEstimates = cards
    .filter(c => Number(c.estimatedBill) > 0)
    .map(c => ({ id: c.id, name: c.name, amount: Number(c.estimatedBill) }))
  const cardEstimateTotal = cardEstimates.reduce((s, c) => s + c.amount, 0)
  const lifeBalance = income - essentialTotal - cardEstimateTotal
  const planSummary = useMemo(() => ({
    monthKey: `${new Date().getFullYear()}-${String(new Date().getMonth() + 1).padStart(2, '0')}`,
    income,
    essentialTotal,
    essentialSavings,
    cardEstimateTotal,
    lifeBalance,
  }), [income, essentialTotal, essentialSavings, cardEstimateTotal, lifeBalance])

  // 每次開 App 檢查一次：如果有設定雲端同步、且距上次同步超過一週，就在背景默默
  // 補一次同步。只用靜默換 token（不彈同意畫面），換不到就放棄，等下次開 App 或
  // 使用者自己手動同步；每個 session 只嘗試一次，避免每次資料變動就重打 API。
  useEffect(() => {
    if (autoSyncAttempted.current) return
    const clientId = googleSync?.clientId?.trim()
    const sheetId = googleSync?.sheetId?.trim()
    if (!clientId || !sheetId) return
    const WEEK_MS = 7 * 24 * 60 * 60 * 1000
    if (googleSync?.lastSyncAt && Date.now() - googleSync.lastSyncAt < WEEK_MS) return

    autoSyncAttempted.current = true
    ;(async () => {
      const token = await getAccessTokenSilent(clientId)
      if (!token) return
      try {
        const count = await syncTransactionsToSheet({ accessToken: token, sheetId, transactions })
        await syncBillingCyclesToSheet({ accessToken: token, sheetId, cards })
        if (planSummary.income > 0) {
          await syncMonthlyPlanToSheet({ accessToken: token, sheetId, summary: planSummary })
        }
        setGoogleSync(prev => ({ ...prev, lastSyncAt: Date.now(), lastSyncCount: count }))
        showToast(`已自動同步 ${count} 筆刷卡紀錄`)
      } catch {
        // 靜默失敗（例如網路問題），不打擾使用者，等下次開 App 再試
      }
    })()
  }, [googleSync, cards, transactions, planSummary, showToast])

  const weekDays = buildWeekDays(plans, enrichedCards, transactions)
  const enrichedPlans = enrichPlans(plans, transactions)

  // 蝜唾祥??嚗?瘥撐?～??蝜喟??望??文像??蝑?蝑?????撘萄?航?????蝜喉?嚗?
  // 憭拇?函?甇???交??豢?嚗?????敶梢??
  const paymentReminders = enrichedCards
    .flatMap(c => {
      const reserve = savings.find(g => g.linkedCardId === c.id)
      return c.unpaidCycles.map(cycle => ({
        id: cycle.id,
        cardId: c.id,
        name: c.name,
        color: c.color,
        amount: cycle.amount,
        dueDateLabel: `${Number(cycle.dueDate.slice(5, 7))}/${Number(cycle.dueDate.slice(8, 10))}`,
        daysLeft: cycle.daysLeft,
        reserve: reserve ? { id: reserve.id, name: reserve.name, saved: Number(reserve.saved) } : null,
      }))
    })
    .sort((a, b) => a.daysLeft - b.daysLeft)

  // ???嚗?銝???鞎駁??董??
  const dashboardCards = enrichedCards.map(c => {
    const reserve = savings.find(g => g.linkedCardId === c.id)
    return {
      ...c,
      reserve: reserve ? { id: reserve.id, name: reserve.name, saved: Number(reserve.saved) } : null,
    }
  })

  // ?? App ???交?敹怠???暹??鞎餃停頝喃??汗?券嚗?憭拙頝喃?甈∴?
  useEffect(() => {
    maybeNotifyDueBills(paymentReminders)
  }, [paymentReminders])

  // ?芸?鞎嚗??Ｚ??菜??堆?嚗閮??蝜單??擗???? 瘥???
  const liabilityItems = plans
    .filter(p => p.type === 'installment' && p.totalCount - installmentPaidCount(p, transactions) > 0)
    .map(p => {
      const remainingPeriods = p.totalCount - installmentPaidCount(p, transactions)
      return {
        id: p.id,
        name: p.name,
        card: p.card,
        perPeriod: p.amount,
        remainingPeriods,
        outstanding: remainingPeriods * p.amount,
      }
    })
  const totalDebt = liabilityItems.reduce((s, i) => s + i.outstanding, 0)

  const now = new Date()
  const greeting = getGreeting(now.getHours())
  const dateLabel = `${now.getMonth() + 1} 月 ${now.getDate()} 日・${WEEKDAY_NAMES[now.getDay()]}`

  const pages = {
    dashboard: (
      <Dashboard
        greeting={greeting}
        dateLabel={dateLabel}
        currentMonth={currentMonth}
        weekDays={weekDays}
        cards={dashboardCards}
        categories={categories}
        trends={trends}
        liabilityItems={liabilityItems}
        totalDebt={totalDebt}
        envelopeView={envelopeView}
        envelopeSummary={envelopeSummary}
        paymentReminders={paymentReminders}
        onMarkCardPaid={handleMarkCardPaid}
        onMarkAllCyclesPaid={handleMarkAllCyclesPaid}
        onUpdateCycle={handleUpdateCycle}
        income={income}
        essentialTotal={essentialTotal}
        cardEstimateTotal={cardEstimateTotal}
        lifeBalance={lifeBalance}
        onGoToChecklist={() => setTab('checklist')}
      />
    ),
    transactions: (
      <Transactions
        showToast={showToast}
        transactions={transactions}
        cards={cards}
        plans={plans}
        onAddTransaction={handleAddTransaction}
        onUpdateTransaction={handleUpdateTransaction}
        onDeleteTransaction={handleDeleteTransaction}
        onConvertToInstallment={handleConvertToInstallment}
        onMarkAsSubscription={handleMarkAsSubscription}
        cardImport={cardImport}
        importingCardNotifications={importingCardNotifications}
        onImportCardNotifications={handleImportCardNotifications}
      />
    ),
    checklist: (
      <Checklist
        showToast={showToast}
        items={checklist}
        monthName={currentMonth.name}
        income={income}
        essentialTotal={essentialTotal}
        checklistTotal={checklistTotal}
        savingsMonthly={savingsMonthly}
        essentialSavings={essentialSavings}
        lifeBalance={lifeBalance}
        cardEstimates={cardEstimates}
        cardEstimateTotal={cardEstimateTotal}
        onUpdateEstimatedBill={handleUpdateEstimatedBill}
        savings={savings}
        cardBills={cards.map(c => ({ id: c.id, name: c.name, bill: Number(c.estimatedBill) || 0 }))}
        onIncomeChange={setIncome}
        onAdd={handleAddChecklistItem}
        onToggle={handleToggleChecklistItem}
        onUpdate={handleUpdateChecklistItem}
        onDelete={handleDeleteChecklistItem}
        onAddSaving={handleAddSaving}
        onUpdateSaving={handleUpdateSaving}
        onDeleteSaving={handleDeleteSaving}
        onContributeSaving={handleContributeSaving}
        onSpendSaving={handleSpendSaving}
        onResetSaving={handleResetSaving}
        plans={enrichedPlans}
        cards={cards}
        fxSettings={fxSettings}
        onAddPlan={handleAddPlan}
        onUpdatePlan={handleUpdatePlan}
        onDeletePlan={handleDeletePlan}
        onMarkPlanPaid={handleMarkPaid}
      />
    ),
    settings: (
      <Settings
        showToast={showToast}
        cards={cards}
        fxSettings={fxSettings}
        envelopes={envelopes}
        onFxChange={setFxSettings}
        onAddCard={handleAddCard}
        onSaveCard={handleSaveCard}
        onDeleteCard={handleDeleteCard}
        onAddEnvelope={handleAddEnvelope}
        onUpdateEnvelope={handleUpdateEnvelope}
        onDeleteEnvelope={handleDeleteEnvelope}
        backupData={{ cards, plans, transactions, checklist, checklistMonth, envelopes, fxSettings, income, savings, googleSync, cardImport }}
        onImportData={handleImportData}
        onClearData={handleClearData}
        transactions={transactions}
        googleSync={googleSync}
        onGoogleSyncChange={setGoogleSync}
        cardImport={cardImport}
        onCardImportChange={setCardImport}
        planSummary={planSummary}
      />
    ),
  }

  if (cards.length === 0 && tab !== 'settings') {
    return (
      <div className="app-root">
        <Onboarding onStart={() => setTab('settings')} />
        {toast && <Toast message={toast.message} onUndo={toast.onUndo} />}
      </div>
    )
  }

  return (
    <div className="app-root">
      <main className="app-page">
        {pages[tab]}
      </main>
      <BottomNav active={tab} onChange={setTab} />
      {toast && <Toast message={toast.message} onUndo={toast.onUndo} />}
    </div>
  )
}
